#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

# Base cookbooks required by Hatch
cookbook "chef-client"
cookbook "chef-server"
cookbook "hatch",
  :path => "hatch/cookbook"

# Patched Opscode cookbook for Ubuntu 12.04
cookbook "java",
  :git => "https://github.com/cjAdvertising/chef-java.git"